let socket = null;
let activeTabId = null;

let recording = false;

/*
 * recordingStartedAt is persisted in chrome.storage.session
 * (not memory) because MV3 service workers are terminated
 * after ~30s idle and restarted on the next event. The
 * offscreen recorder keeps running across those restarts,
 * so any state it depends on must survive them.
 */

/*
 * Meeting identity (architecture.md Rule 6):
 * The meeting_id belongs to the MEETING, not to a
 * WebSocket connection or service-worker lifetime.
 * It is generated by the extension when the call is
 * first detected and kept in chrome.storage.session
 * so it survives WebSocket reconnects and service
 * worker restarts until the recording is uploaded.
 */

const ACTIVE_MEETING_KEY = "activeMeeting";

async function getActiveMeeting() {
    const result = await chrome.storage.session.get(
        ACTIVE_MEETING_KEY
    );
    return result[ACTIVE_MEETING_KEY] || null;
}

async function ensureMeetingId(tabId) {
    const existing = await getActiveMeeting();

    if (existing) {
        if (existing.tabId === tabId) {
            return existing.meetingId;
        }
        console.warn(
            "[BG] New meeting in another tab, replacing:",
            existing.meetingId
        );
    }

    const meetingId = crypto.randomUUID();

    await chrome.storage.session.set({
        activeMeeting: {
            meetingId: meetingId,
            tabId: tabId,
            startedAt: Date.now()
        }
    });

    console.log("[BG] Meeting ID:", meetingId);

    return meetingId;
}

async function clearActiveMeeting(meetingId) {
    const existing = await getActiveMeeting();

    if (existing && existing.meetingId === meetingId) {
        await chrome.storage.session.remove(
            ACTIVE_MEETING_KEY
        );
    }
}

async function setRecordingStartedAt(ts) {
    await chrome.storage.session.set({
        recordingStartedAt: ts
    });
}

async function getRecordingStartedAt() {
    const result = await chrome.storage.session.get(
        "recordingStartedAt"
    );
    return result.recordingStartedAt || null;
}

async function clearRecordingStartedAt() {
    await chrome.storage.session.remove(
        "recordingStartedAt"
    );
}


function connectWebSocket() {

    console.log("[BG] Connecting to backend...");


    socket =new WebSocket("ws://127.0.0.1:8000/ws");
    socket.onopen = () => {
        console.log(
            "[BG] Connected to backend"
        );
    };

    socket.onmessage = (event) => {
        try {
            const message =JSON.parse(event.data);

            console.log("[BG] Backend:",message);

            if (message.type === "summary" || message.type === "snapshot") {
                if (activeTabId === null) {
                    return;
                }
                chrome.tabs.sendMessage(activeTabId, message);
            }


            if (message.type === "meeting_started") {
                console.log(
                    "[BG] Backend meeting:",
                    message.meeting_id
                );

                if (activeTabId !== null) {
                    chrome.tabs.sendMessage(activeTabId, message);
                }
            }


            if (message.type === "final_processing_started") {

                if (activeTabId !== null) {
                    chrome.tabs.sendMessage(activeTabId, message);
                }
            }


            if (message.type === "final_processing_complete") {
                if (activeTabId !== null) {
                    chrome.tabs.sendMessage(activeTabId, message);
                }
            }

        } catch (error) {
            console.error("[BG] Parse error:", error);
        }
    };


    socket.onclose = () => {

        console.log("[BG] Disconnected");

        socket = null;

        setTimeout(connectWebSocket, 2000);
    };


    socket.onerror = (error) => {
        console.error("[BG] WebSocket error:", error);
    };
}

connectWebSocket();

if (chrome.alarms) {
    chrome.alarms.create("keepalive", { periodInMinutes: 0.4 });

    chrome.alarms.onAlarm.addListener((alarm) => {
        if (alarm.name === "keepalive") {
            if (!socket || socket.readyState !== WebSocket.OPEN) {
                connectWebSocket();
            }
        }
    });
} else {
    console.warn(
        "[Sales AI] chrome.alarms unavailable - " + "reload the extension from chrome://extensions"
    );
}

// Offscreen Document 

async function ensureOffscreenDocument() {

    const offscreenUrl = chrome.runtime.getURL("offscreen.html");

    const existingContexts = await chrome.runtime.getContexts({
                contextTypes: [
                    "OFFSCREEN_DOCUMENT"
                ],
                documentUrls: [
                    offscreenUrl
                ]
            });


    if (existingContexts.length > 0) {
        return;
    }


    await chrome.offscreen.createDocument({
        url: "offscreen.html",
        reasons: [
            "USER_MEDIA",
            "AUDIO_PLAYBACK"
        ],
        justification:
            "Record Google Meet audio locally for post-call transcription, " +
            "and play the captured tab audio back out so the user keeps " +
            "hearing the call while it is being recorded."
    });

}


// Start Audio Capture
async function startAudioRecording() {
    if (recording) {
        console.log("[AUDIO] Already recording");
        return;
    }
    if (activeTabId === null) {
        console.error("[AUDIO] No active Meet tab");
        return;
    }

    try {
        await ensureOffscreenDocument();
        const streamId = await chrome.tabCapture.getMediaStreamId({ targetTabId: activeTabId });
        console.log("[AUDIO] Stream ID acquired");

        recording = true;

        chrome.runtime.sendMessage({
            type:
                "audio_recording_state",

            recording:
                true
        });


        await chrome.runtime.sendMessage({
            type:
                "start_audio_recording",

            streamId:
                streamId
        });
        console.log("[AUDIO] Recording requested");


    } catch (error) {
        recording = false;
        console.error("[AUDIO] Capture failed:", error);

        if (activeTabId !== null) {
            chrome.tabs.sendMessage(
                activeTabId,
                {
                    type: "audio_recording_error",
                    error: error.message
                }
            );
        }
    }
}

// Stop Audio Capture.
// The in-memory `recording` flag is wiped by every MV3
// service-worker restart, so it must NOT gate the stop
// flow. The source of truth is the offscreen document:
// it survives SW restarts and owns the live MediaRecorder.
async function stopAudioRecording() {
    recording = false;

    clearRecordingStartedAt();

    try {
        const offscreenUrl =
            chrome.runtime.getURL("offscreen.html");

        const contexts =
            await chrome.runtime.getContexts({
                contextTypes: [
                    "OFFSCREEN_DOCUMENT"
                ],
                documentUrls: [offscreenUrl]
            });

        if (contexts.length === 0) {
            console.log(
                "[AUDIO] No offscreen document; nothing to stop"
            );
            return;
        }

        await chrome.runtime.sendMessage({
            type: "stop_audio_recording"
        });

        console.log("[AUDIO] Stop requested");
    } catch (error) {
        console.error("[AUDIO] Stop failed:", error);
    }
}

// Extension Messages
chrome.runtime.onMessage.addListener(
    (message, sender) => {
        // Transcript
        if (message.type === "transcript") {
            if (sender.tab && sender.tab.id !== undefined) {
                activeTabId = sender.tab.id;
            }

            getActiveMeeting().then((active) => {
                if (socket && socket.readyState === WebSocket.OPEN) {
                    socket.send(
                        JSON.stringify({
                            type: "transcript",
                            speaker: message.speaker,
                            text: message.text,
                            timestamp: message.timestamp,
                            meeting_id: active
                                ? active.meetingId
                                : null
                        })
                    );
                }
            });
        }

        if (message.type === "snapshot_interval") {
            getActiveMeeting().then((active) => {
                if (socket && socket.readyState === WebSocket.OPEN) {
                    socket.send(JSON.stringify({
                            type: "snapshot_interval",
                            minutes: message.minutes,
                            meeting_id: active
                                ? active.meetingId
                                : null
                        })
                    );
                }
            });
        }

        // start audio 
        if (message.type === "start_audio_recording") {
            if (sender.tab && sender.tab.id !== undefined) {
                activeTabId = sender.tab.id;
            }
            startAudioRecording();
        }

        // stop audio 
        if (message.type === "stop_audio_recording") {
            stopAudioRecording();
        }

        // download report file
        if (message.type === "download_report") {
            const fullUrl = `http://127.0.0.1:8000${message.url}`;

            // Capture the requesting tab now, at message-receipt time.
            // The module-level activeTabId is unreliable here: MV3
            // service workers are evicted after ~30s idle and reset
            // it to null on restart. Since the click happens well
            // after that window (call already ended), activeTabId is
            // frequently null again by the time onChanged fires,
            // which was silently dropping download_complete/
            // download_error and leaving the widget's recovery state
            // stuck forever. sender.tab.id is stable for this whole
            // closure regardless of SW eviction in between.
            const requestingTabId =
                (sender.tab && sender.tab.id !== undefined)
                    ? sender.tab.id
                    : activeTabId;

            chrome.downloads.download(
                {
                    url: fullUrl,
                    filename: message.filename,
                    saveAs: false
                },
                (downloadId) => {
                    if (chrome.runtime.lastError) {
                        console.error("[DOWNLOAD] Failed:", chrome.runtime.lastError.message);

                        if (requestingTabId !== null) {
                            chrome.tabs.sendMessage(requestingTabId, {
                                type: "download_error",
                                error: chrome.runtime.lastError.message
                            });
                        }
                        return;
                    }

                    console.log("[DOWNLOAD] Started, id:", downloadId);

                    const onChanged = (delta) => {
                        if (delta.id !== downloadId) return;

                        if (delta.state) {
                            if (delta.state.current === "complete") {
                                console.log("[DOWNLOAD] Complete:", message.filename);

                                if (requestingTabId !== null) {
                                    chrome.tabs.sendMessage(requestingTabId, {
                                        type: "download_complete",
                                        filename: message.filename
                                    });
                                }
                            } else if (delta.state.current === "interrupted") {
                                console.error("[DOWNLOAD] Interrupted");

                                if (requestingTabId !== null) {
                                    chrome.tabs.sendMessage(requestingTabId, {
                                        type: "download_error",
                                        error: "Download interrupted"
                                    });
                                }
                            }

                            chrome.downloads.onChanged.removeListener(onChanged);
                        }
                    };

                    chrome.downloads.onChanged.addListener(onChanged);
                }
            );
        }
 
        // audio started
        if (message.type === "audio_recording_started") {
            recording = true;
            setRecordingStartedAt(Date.now());

            if (activeTabId !== null) {
                chrome.tabs.sendMessage(
                    activeTabId,
                    message
                );
            }
        }

        // audio error
        if (message.type === "audio_recording_error") {
            recording = false;
            clearRecordingStartedAt();

            if (activeTabId !== null) {
                chrome.tabs.sendMessage(
                    activeTabId,
                    message
                );
            }
        }

        // audio complete
        if (message.type === "audio_recording_complete") {
            recording = false;

            if (!message.audioBase64) {
                console.error("[AUDIO] Recording is empty, skipping upload");
                return;
            }

            console.log("[AUDIO] Recording complete:", message.size, "bytes");

            uploadAudio(message.audioBase64);
        }

        if (message.type === "meet_session_started") {
            if (sender.tab && sender.tab.id !== undefined) {
                activeTabId = sender.tab.id;

                console.log("[MEET] Session started.", activeTabId);

                ensureMeetingId(activeTabId);

            }
        }

        if (message.type === "meet_session_ended") {
            console.log("[MEET] Session ended");

            // Tell the backend the meeting is over so live
            // summaries and snapshots stop, even though the
            // WebSocket stays open during upload.
            getActiveMeeting().then((active) => {
                if (
                    socket &&
                    socket.readyState === WebSocket.OPEN &&
                    active
                ) {
                    socket.send(JSON.stringify({
                        type: "meeting_ended",
                        meeting_id: active.meetingId
                    }));
                }
            });

            stopAudioRecording();
        }

    }
);

// click listener 
chrome.action.onClicked.addListener(async (tab) => {
    activeTabId = tab.id; 


    const existing = await getActiveMeeting();

    if (!existing || existing.tabId !== tab.id) {
        await ensureMeetingId(tab.id);
    }
    await startAudioRecording();
})

// Upload Audio to Backend

async function uploadAudio(audioBase64) {
    const active = await getActiveMeeting();

    if (!active || !active.meetingId) {
        console.error("[AUDIO] No active meeting ID available");
        return;
    }

    const meetingId = active.meetingId;
    const startedAt = await getRecordingStartedAt();

    console.log(
        "[AUDIO] Uploading recording for meeting",
        meetingId
    );

    try {
        const binary = atob(audioBase64);
        const bytes = new Uint8Array(binary.length);
        for (let i = 0; i < binary.length; i++) {
            bytes[i] = binary.charCodeAt(i);
        }

        const blob = new Blob([bytes], {
                type: "audio/webm"
            }
        );
        const formData = new FormData();

        formData.append("file", blob, "meeting.webm");

        formData.append("meeting_id", meetingId);

        if (startedAt) {
            formData.append(
                "recording_started_at",
                String(startedAt)
            );
        }

        const response =
            await fetch(
                "http://127.0.0.1:8000/audio/upload",
                {
                    method: "POST",
                    body: formData
                }
            );
        if (!response.ok) {
            throw new Error(
                `Upload failed: ${response.status}`
            );
        }
        const result = await response.json();
        console.log("[AUDIO] Backend result:", result);

        await clearActiveMeeting(meetingId);

        if (activeTabId !== null) {
            chrome.tabs.sendMessage(
                activeTabId,
                result
            );
        }

    } catch (error) {
        console.error("[AUDIO] Upload error:", error);

        if (activeTabId !== null) {
            chrome.tabs.sendMessage(
                activeTabId,
                {
                    type: "audio_recording_error",
                    error: error.message
                }
            );
        }
    }
}